### ISSUE TITLE
Exception debug information is almost useless

### ISSUE THREAD

**Issue by kflu** [HtmlUnit/NHtmlUnit#12]
So I hit an exception while getting page using WebClient. But the exception information is nearly useless. I believe the .Net wrapper somehow wraps the exception but discarded the useful diagnostic information. 

This severely limits the diagnosability. Please fix.

```
System.InvalidOperationException was unhandled by user code
  HResult=-2146233079
  Message=Operation is not valid due to the current state of the object.
  Source=NHtmlUnit
  StackTrace:
       at NHtmlUnit.ObjectWrapper.CreateWrapper[T](Object wrappedObject)
       at NHtmlUnit.WebClient.GetPage(String url)
       at TestProject.TestProject.TryDownloadOne(DownloadSpec spec, FlexUri uri, String& content) in c:\Users\myuser\Documents\Visual Studio 2013\Projects\TestProject\TestProject\TestProject.cs:line 101
       at TestProject.TestProject.DownloadAll() in c:\Users\myuser\Documents\Visual Studio 2013\Projects\TestProject\TestProject\TestProject.cs:line 52
       at TestProjectTestCases.UnitTest1.TestMethod1() in c:\Users\myuser\Documents\Visual Studio 2013\Projects\TestProject\TestProjectTestCases\UnitTest1.cs:line 19
  InnerException: 
```

**Comment by asbjornu** [comment]
@kflu Do you have any way to reproduce this? If not, I have no idea how to figure this one out.
