### ISSUE TITLE
unable to connect website with TLS1.2 only

### ISSUE THREAD

**Issue by jatpat** [HtmlUnit/NHtmlUnit#33]
Hello,

I am facing error while connecting website running with TLS1.2 protocol only.

following is the error:

  ```
Received fatal alert: handshake_failure

 at org.apache.http.impl.execchain.RetryExec.execute(HttpRoute route, HttpRequestWrapper request, HttpClientContext context, HttpExecutionAware execAware)

   at org.apache.http.impl.execchain.RedirectExec.execute(HttpRoute route, HttpRequestWrapper request, HttpClientContext context, HttpExecutionAware execAware)

   at org.apache.http.impl.client.InternalHttpClient.doExecute(HttpHost , HttpRequest , HttpContext )

   at org.apache.http.impl.client.CloseableHttpClient.execute(HttpHost target, HttpRequest request, HttpContext context)

   at com.gargoylesoftware.htmlunit.HttpWebConnection.getResponse(WebRequest request)

   at com.gargoylesoftware.htmlunit.WebClient.loadWebResponseFromWebConnection(WebRequest , Int32 )

   at com.gargoylesoftware.htmlunit.WebClient.loadWebResponse(WebRequest webRequest)

   at com.gargoylesoftware.htmlunit.WebClient.getPage(WebWindow webWindow, WebRequest webRequest)

   at com.gargoylesoftware.htmlunit.WebClient.getPage(URL url)

   at com.gargoylesoftware.htmlunit.WebClient.getPage(String url)

   at NHtmlUnit.WebClient.GetPage(String url)

   at NHtmlUnit.WebClient.GetHtmlPage(String url)

```

**Comment by Ruslancahan** [comment]
Did u solve the issue?
I can't. Please help me

**Comment by asbjornu** [comment]
I wouldn't expect this project to receive an update before IKVM is ported to .NET Core. See #35 for details.
